### ISSUE TITLE
Chicken Man Not Authenticating/Generating Handshakes

### ISSUE THREAD

**Issue by firewallzer0** [skickar/ChickenManGame#4]
I have setup the D1 mini's per instructions but chicken man is not connecting or generating handshakes. It attempts to connect but fails all five times and then goes to sleep. I have observed the console output of both units and they appear to be using the same password. I can also connect to the chicken without issue. I have sniffed the traffic and was not able to catch any and shakes after 10 minutes.

Things I have tried to resolve this issue:
* Swapping hardware of the chickman
* Swapping hardware of the chicken
* Recompiling and loading the firmware.
* Redownloaded, recompiling, and reloading the firmware.

I am including a screenshot of the console output from chicken man. 
![image](https://user-images.githubusercontent.com/25125427/72201286-7c225500-340f-11ea-803b-a53fda7512ae.png)

**Comment by brandonpaiz** [comment]
Just confirmed this bug in master. Switching over to the `duel` branch should resolve the issue. If it does, I'll merge so others won't run into this problem.

Thanks for raising the issue!

**Comment by firewallzer0** [comment]
I switched to `duel` as suggested and I am seeing some authentications, but I am also seeing Chicken Man Crashing, sometimes not connecting and then resetting. Chickens do not generate any additional output except when there is a successful connection. Images and text below.

What I have done:
* Updated all the D1 minis with the `duel` branch code.

# Crash text below:

> Chicken_Easy_03                  - Chicken

> -> Connecting to 'Chicken_Easy_03' with password '1q2w3e4r'...
> Exception (9):
> epc1=0x40212d74 epc2=0x00000000 epc3=0x00000000 excvaddr=0x03ce0423 depc=0x00000000
> 
> >>>stack>>>
> 
> ctx: cont
> sp: 3ffffcd0 end: 3fffffc0 offset: 01a0
> 3ffffe70:  007a1200 7973622c 3ffef148 4020913c  
> 3ffffe80:  3ffe91e6 3ffef448 3ffef148 40209e84  
> 3ffffe90:  0000001e 3ffef0c0 3ffef148 4020a230  
> 3ffffea0:  4023ffc3 0000001e 3ffffee8 402100fc  
> 3ffffeb0:  3ffffee8 3ffffee8 3ffe91e6 40210132  
> 3ffffec0:  00008782 3ffef448 3ffef0c0 40203a82  
> 3ffffed0:  402133b8 00000000 00001388 fffffffe  
> 3ffffee0:  3ffef2a4 00000000 3fff1994 001e001f  
> 3ffffef0:  00fe925f 00000000 4bc6a7f0 00000000  
> 3fffff00:  77327131 72346533 88100400 3fff1aac  
> 3fffff10:  000f000f 00fef448 3ffe925d 4020f210  
> 3fffff20:  00000005 3ffef148 00000010 4020f535  
> 3fffff30:  3ffef06c 3ffef448 3ffef0c0 3ffef064  
> 3fffff40:  3ffef06c 3ffef448 3ffef0c0 40202cff  
> 3fffff50:  feefeffe feefeffe feefeffe feefeffe  
> 3fffff60:  007a1200 5a34f900 feefef00 feefeffe  
> 3fffff70:  00000000 feefeffe feefeffe feefeffe  
> 3fffff80:  00000000 00000000 00000001 401003ec  
> 3fffff90:  3fffdad0 00000000 3ffef554 3ffef594  
> 3fffffa0:  3fffdad0 00000000 3ffef554 402112ac  
> 3fffffb0:  feefeffe feefeffe 3ffe84e8 40100f25  
> <<<stack<<<
> 
>  ets Jan  8 2013,rst cause:4, boot mode:(3,6)
> 
> wdt reset
> load 0x4010f000, len 1392, room 16 
> tail 0
> chksum 0xd0
> csum 0xd0
> v3d128e5c
> ~ld
> Starting
> Mode: Chicken Man
> Revived Chicken Man
# Crash Image
![Crash](https://user-images.githubusercontent.com/25125427/72209883-e15a6280-3470-11ea-855b-b3526d5c09ff.png)


I am also seeing inconsistent behavior. Which cause Chicken Man to never be able to connect to two different Chickens before resetting.

With this screenshot I have only 1 chicken running.


![inconsitantly connecting](https://user-images.githubusercontent.com/25125427/72209948-a1e04600-3471-11ea-89b7-9c2d6c321d7d.png)

**Comment by brandonpaiz** [comment]
Uh-oh. We are looking into it.

**Comment by firewallzer0** [comment]
Let me know if there is anything I can do to help, not much of a coder but I will see if I can find anything too. I'll be around for the next 2 hours and then again tomorrow all day. Happy to do testing or provide any additional information needed.

**Comment by firewallzer0** [comment]
Quick update, I changed the connection time out from 2000ms to 5000ms using the master branch and started getting connections however I am still suffering the same errors random crashes and resets.

What I've done:
* Updated line 195 of `Man.cpp` from the `master` branch from 2000 to 5000
* Uploaded code to just ChickenMan
* Powered up 5 Chickens

# Screenshot
![image](https://user-images.githubusercontent.com/25125427/72211701-f644ef00-348c-11ea-834d-3a479a9bab53.png)

**Comment by brandonpaiz** [comment]
Okay I pushed a commit to the `duel` branch that fixed it for me. Would you like to try it out?

**Comment by firewallzer0** [comment]
Checked it out, everything looks good to me. No more crashing and I am getting handshakes. Thanks for getting to this so fast!

**Comment by brandonpaiz** [comment]
Awesome! I'll apply this to master when I get the chance. You're welcome; thanks for playing!

**Comment by brandonpaiz** [comment]
For documentation, the issue was that the ESP8266 Arduino API 2.5 ESP8266HTTPClient had changed the definition of http.begin
[Bug fix](https://github.com/skickar/ChickenManGame/commit/cec8c6ae0b5a7ce440d2c0e012d42c186370c14c)

**Comment by atz-dev** [comment]
Hello @brandonpaiz, 
I just set up a Chicken and a Chicken Man from the main branch, but I have the same problem as this issue.
The password is good on the Chicken Man logs, but impossible to connect to the access point: it gives "no luck :(" in a loop.
Any advise ? Everything else works so that's the only thing I miss !
