### ISSUE TITLE
Chicken won't turn into chickenman

### ISSUE THREAD

**Issue by Atilaeus** [skickar/ChickenManGame#6]
I have a jumper wire going from D7 to GND and it stays as a chicken. Could I possibly get a picture of the wire set-up itself? I tried to watch the youtube video in the read me but it is private.

**Comment by brandonpaiz** [comment]
I'll bother Kody about the video.
Make sure you connect D7 to ground *before* powering on the ESP8266. If that doesn't work try hitting the reset button three times quickly while the ESP8266 is connected to power. Let me know if it still doesn't work!

**Comment by Atilaeus** [comment]
I've tried this a few times and still same results :(
I may not be fully understanding how to properly use the breadboard. I am putting a wire connector in J47 on my breadboard which is next to the D7 pin of the esp8266 (which is in I47) then I am putting the opposite end of that wire connector to the hole next to the GND pin on the esp8266. I have also tried to put the "ground" end in the negative bank. Thank you so much for taking the time to help me. I really do appreciate your time.

**Comment by brandonpaiz** [comment]
Hey thanks for being patient! Can you bridge a wire directly from D7 to ground while the ESP8266 is  unplugged? [Like this](https://i.imgur.com/itwaFFm.jpg). Then, what does the serial monitor tell you (set it to baud rate 115200)?

**Comment by Atilaeus** [comment]
I just bought a D1 mini like you have there. I had the NodeMCU and it came pre-soldered so I couldn't insert pins directly to it to connect the D7 and GND since the pins were sticking out the bottom. It comes in Friday and I will try these steps. Again, thank you so much for your time and patience, I'm learning a whole lot through all this! Please pass my thanks to Kody as well, can't wait to check out the walk through video!

**Comment by Atilaeus** [comment]
Holy cow I GOT IT TO WORK! Thank you sooooooo much! I really appreciate the visual, definitely helped me figure out what I was doing wrong. Thank you so much!

**Comment by brandonpaiz** [comment]
Hey, congrats! Have fun playing!
