### ISSUE TITLE
Game restart

### ISSUE THREAD

**Issue by LosBagros** [skickar/ChickenManGame#9]
How to restart game from Cooked_Chicken

**Comment by LosBagros** [comment]
It randomly worked but idk how to reset the game properly

**Comment by brandonpaiz** [comment]
Hi @LosBagros
I don't have one in front of me but I'm pretty sure you can triple-press the reset button on the esp8266 itself. Let me know how it goes!
@skickar does this sound right?

**Comment by LosBagros** [comment]
Yes it worked.

Thanks
Bagros
